---
creation_rules:
  - kms: 'arn:aws:kms:us-east-1:<>:key/33990a42-e007-42db-8f29-01c7dbd54610'
    path_regex: .*/dev/.*
  - kms: 'arn:aws:kms:us-east-1:<>:key/4715f83a-e2ec-4e4f-8f5e-1b0984376b14'
    path_regex: .*/qa/.*
